# Generated by Django 5.0.3 on 2024-03-26 17:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0004_rename_userblocked_blockeduser"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="userfollow",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="userfollow",
            name="followed_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="following",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="userfollow",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="followed_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="userfollow",
            constraint=models.UniqueConstraint(
                fields=("followed_user", "user"), name="unique_follow"
            ),
        ),
    ]
