# Generated by Django 5.0.3 on 2024-03-28 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0007_remove_userfollow_unique_follow_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="userfollow",
            name="unique_follow",
        ),
        migrations.AddConstraint(
            model_name="userfollow",
            constraint=models.UniqueConstraint(
                fields=("user", "followed_user"), name="unique_follow"
            ),
        ),
    ]
