# Generated by Django 5.0.3 on 2024-03-19 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserFollow',
        ),
    ]
