# Generated by Django 5.0.3 on 2024-03-14 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0002_review_image_alter_review_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='description',
            field=models.TextField(blank=True, max_length=2048),
        ),
    ]
