# Generated by Django 5.0.3 on 2024-03-14 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0003_review_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='title',
            field=models.CharField(default='', max_length=128),
        ),
    ]
