# Generated by Django 5.0.3 on 2024-03-14 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0005_alter_ticket_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='description',
        ),
        migrations.RemoveField(
            model_name='review',
            name='image',
        ),
        migrations.RemoveField(
            model_name='review',
            name='title',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='title',
            field=models.CharField(max_length=128),
        ),
    ]
